language: cpp

compiler:
    - clang

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-add-repository -y ppa:smspillaz/cmake-2.8.12; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y cmake cmake-data; fi

os:
    - linux
    - osx

script:
    - mkdir ./out && cd ./out
    - cmake ../
    - cmake --build ./
    - ctest -V
